/**
 * Electron main process for Pomo app.
 * Manages: main window, blocking overlay window, system tray, notifications,
 * IPC handlers, and timer coordination.
 */

const { app, BrowserWindow, ipcMain, screen, Tray, Menu, nativeImage, Notification } = require('electron');
const path = require('path');
const { v4: uuidv4 } = require('uuid');
const { initDB, saveSession, getTodaySessions, getYesterdaySessions, getTodayPomodoroCount } = require('./db');

let mainWindow    = null;
let blockingWindow = null;
let tray          = null;
let currentSession = null; // { startTime, pomodoroNumber }
let trayLabel     = 'Pomo'; // updated by renderer ticks

// ── Tray icon ─────────────────────────────────────────────────────────────────
/**
 * Load the tray icon PNG from assets/.
 * The PNG was pre-generated by Python at install time.
 * @returns {Electron.NativeImage}
 */
function makeTrayIcon() {
  // We display via tray.setTitle() emoji, so use an empty image to avoid
  // a duplicate icon dot appearing next to the text.
  return nativeImage.createEmpty();
}

// ── Windows ───────────────────────────────────────────────────────────────────

/**
 * Create (or show) the main application window.
 */
function createMainWindow() {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.show();
    mainWindow.focus();
    return;
  }

  mainWindow = new BrowserWindow({
    width: 1100,
    height: 720,
    minWidth: 900,
    minHeight: 600,
    title: 'Pomo',
    backgroundColor: '#1a1a2e',
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  mainWindow.loadFile(path.join(__dirname, 'renderer', 'index.html'));

  // Hide instead of close so the tray keeps the app alive
  mainWindow.on('close', (e) => {
    if (!app.isQuitting) {
      e.preventDefault();
      mainWindow.hide();
      updateTrayMenu();
    }
  });

  mainWindow.on('closed', () => { mainWindow = null; });
}

/**
 * Create the full-screen blocking overlay shown when a pomodoro ends.
 * Stays above all other windows until the user submits accomplishment details.
 */
function createBlockingWindow() {
  // First: fire a macOS notification so the user knows time is up
  if (Notification.isSupported()) {
    const n = new Notification({
      title: '🎯 Focus session complete!',
      body: 'Log what you accomplished to continue.',
      silent: false,
    });
    n.show();
  }

  // Restore and bring main window to front before opening blocker
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.restore();
    mainWindow.show();
  }

  const { width, height } = screen.getPrimaryDisplay().bounds;

  blockingWindow = new BrowserWindow({
    width,
    height,
    x: 0,
    y: 0,
    frame: false,
    resizable: false,
    movable: false,
    alwaysOnTop: true,
    fullscreen: true,
    skipTaskbar: true,
    backgroundColor: '#0d0d1a',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  blockingWindow.loadFile(path.join(__dirname, 'renderer', 'blocker.html'));
  blockingWindow.setAlwaysOnTop(true, 'screen-saver');
  blockingWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  blockingWindow.focus();
  updateTrayMenu();
}

/**
 * Close and destroy the blocking overlay window.
 */
function closeBlockingWindow() {
  if (blockingWindow && !blockingWindow.isDestroyed()) {
    blockingWindow.close();
    blockingWindow = null;
  }
  updateTrayMenu();
}

// ── Tray ──────────────────────────────────────────────────────────────────────

/**
 * Create the system tray icon and initial context menu.
 */
function createTray() {
  const icon = makeTrayIcon();
  tray = new Tray(icon);
  tray.setTitle('🍅');
  tray.setToolTip('Pomo — click to show');

  // Single click → show/hide main window
  tray.on('click', () => {
    if (mainWindow && !mainWindow.isDestroyed() && mainWindow.isVisible()) {
      mainWindow.hide();
    } else {
      createMainWindow();
    }
    updateTrayMenu();
  });

  updateTrayMenu();
}

/**
 * Rebuild the tray context menu with current state.
 * Called whenever phase/label changes or window visibility changes.
 */
function updateTrayMenu() {
  if (!tray) return;

  const isVisible  = mainWindow && !mainWindow.isDestroyed() && mainWindow.isVisible();
  const isBlocking = blockingWindow && !blockingWindow.isDestroyed();

  const menu = Menu.buildFromTemplate([
    {
      label: trayLabel,
      enabled: false,
    },
    { type: 'separator' },
    {
      label: isVisible ? 'Hide Window' : 'Show Window',
      click: () => {
        if (isVisible) { mainWindow.hide(); }
        else { createMainWindow(); }
        updateTrayMenu();
      },
    },
    ...(isBlocking ? [{
      label: '⚠ Waiting for accomplishment log…',
      enabled: false,
    }] : []),
    { type: 'separator' },
    {
      label: 'Quit Pomo',
      click: () => {
        app.isQuitting = true;
        app.quit();
      },
    },
  ]);

  tray.setContextMenu(menu);
  tray.setToolTip(trayLabel);
}

// ── IPC Handlers ──────────────────────────────────────────────────────────────

/** Renderer requests to start a new pomodoro session. */
ipcMain.on('session-start', (event, data) => {
  currentSession = {
    id: uuidv4(),
    startTime: data.startTime,
    pomodoroNumber: data.pomodoroNumber,
    date: new Date().toISOString().split('T')[0],
  };
});

/** Timer finished — open blocking overlay. */
ipcMain.on('pomodoro-ended', () => {
  createBlockingWindow();
});

/**
 * Renderer sends a tick string so the tray label stays in sync.
 * @example ipcRenderer.send('tray-tick', '🍅 34:12 Focus')
 */
ipcMain.on('tray-tick', (event, label) => {
  trayLabel = label;
  if (tray) {
    tray.setTitle(label);
    tray.setToolTip(label);
  }
  updateTrayMenu();
});

/** Blocker window loaded — send session context so it can number the pomodoro. */
ipcMain.handle('get-current-session', () => currentSession);

/**
 * User submitted accomplishment from blocker window.
 * Saves to DB, closes blocker, notifies main window to refresh list.
 */
ipcMain.handle('submit-accomplishment', async (event, form) => {
  if (!currentSession) return { ok: false, error: 'No active session' };

  const session = {
    id:              currentSession.id,
    date:            currentSession.date,
    start_time:      currentSession.startTime,
    end_time:        form.endTime,
    pomodoro_number: currentSession.pomodoroNumber,
    type:            form.type,
    description:     form.description,
    source:          form.source,
    topic:           form.topic || null,
  };

  try {
    saveSession(session);
    currentSession = null;
    closeBlockingWindow();
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.restore();
      mainWindow.show();
      mainWindow.focus();
      mainWindow.webContents.send('sessions-updated');
    }
    return { ok: true };
  } catch (err) {
    return { ok: false, error: err.message };
  }
});

/** Load today's sessions for the main window. */
ipcMain.handle('get-today-sessions',   () => getTodaySessions());

/** Load yesterday's sessions for the summary modal. */
ipcMain.handle('get-yesterday-sessions', () => getYesterdaySessions());

/** Get today's completed pomodoro count (for numbering). */
ipcMain.handle('get-today-count',      () => getTodayPomodoroCount());

// ── App lifecycle ─────────────────────────────────────────────────────────────

app.whenReady().then(() => {
  initDB();
  createMainWindow();
  createTray();

  // macOS dock click → show main window
  app.on('activate', () => createMainWindow());
});

// Never quit when all windows close — tray keeps the app alive
app.on('window-all-closed', () => {
  // do nothing on macOS; tray icon keeps app running
  if (process.platform !== 'darwin') app.quit();
});

app.on('before-quit', () => { app.isQuitting = true; });
